environment:
    nodejs_version: "6"

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - node --version
    - npm --version
    - npm test

after_test:
    - node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info 

build: off
